#\u4E0D\u542F\u7528spring security
#security:
#  basic:
#    enabled: false

server:
  port: 9527
  #context-path: /secure

security:
  #browser:
   #loginPage: /demo-login.html
    #loginType: REDIRECT
  code:
    image:
      length: 5
      width: 100
      url: /test,/user,/user/*

spring:
  session:
    store-type: none
