#\u4E0D\u542F\u7528spring security
#security:
#  basic:
#    enabled: false

server:
  port: 8081
  #context-path: /secure

#security:
  #browser:
   #loginPage: /demo-login.html
    #loginType: REDIRECT

spring:
  session:
    store-type: none
