#\u4E0D\u542F\u7528spring security
#security:
#  basic:
#    enabled: false

server:
  port: 9527
  #context-path: /secure
  #session超时时间 单位秒，默认30分钟
  session:
    timeout: 100

security:
  #browser:
   #loginPage: /demo-login.html
    #loginType: REDIRECT
  code:
    image:
      length: 4
      width: 67
      url: /test,/user,/user/*
    sms:
      url: /test,/user,/user/*

    social:
      qq:
        app-id: 1
        app-Secret: 2

spring:
  session:
    store-type: none

  #数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/security?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=Asia/Shanghai
    username: root
    password: root
